FROM python:3.12-slim AS BUILDER

# Setup the working directory
WORKDIR /app

# Install system dependencies for building Python packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libssl-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip setuptools wheel && \
    pip install -r requirements.txt

# Run the application with fastapi and uvicorn

FROM python:3.12-slim AS RUNNER
WORKDIR /app
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
COPY --from=BUILDER /usr/local/lib/python3.12 /usr/local/lib/python3.12
COPY --from=BUILDER /usr/local/bin /usr/local/bin
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
