# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import weatherpocket_pb2 as weatherpocket__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in weatherpocket_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignUp = channel.unary_unary(
                '/weatherpocket.v1.AuthService/SignUp',
                request_serializer=weatherpocket__pb2.SignUpRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/weatherpocket.v1.AuthService/Login',
                request_serializer=weatherpocket__pb2.LoginRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/weatherpocket.v1.AuthService/Logout',
                request_serializer=weatherpocket__pb2.LogoutRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.Empty.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/weatherpocket.v1.AuthService/RefreshToken',
                request_serializer=weatherpocket__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.GetMe = channel.unary_unary(
                '/weatherpocket.v1.AuthService/GetMe',
                request_serializer=weatherpocket__pb2.GetMeRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.UserResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SignUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUp,
                    request_deserializer=weatherpocket__pb2.SignUpRequest.FromString,
                    response_serializer=weatherpocket__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=weatherpocket__pb2.LoginRequest.FromString,
                    response_serializer=weatherpocket__pb2.AuthResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=weatherpocket__pb2.LogoutRequest.FromString,
                    response_serializer=weatherpocket__pb2.Empty.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=weatherpocket__pb2.RefreshTokenRequest.FromString,
                    response_serializer=weatherpocket__pb2.AuthResponse.SerializeToString,
            ),
            'GetMe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMe,
                    request_deserializer=weatherpocket__pb2.GetMeRequest.FromString,
                    response_serializer=weatherpocket__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weatherpocket.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weatherpocket.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.AuthService/SignUp',
            weatherpocket__pb2.SignUpRequest.SerializeToString,
            weatherpocket__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.AuthService/Login',
            weatherpocket__pb2.LoginRequest.SerializeToString,
            weatherpocket__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.AuthService/Logout',
            weatherpocket__pb2.LogoutRequest.SerializeToString,
            weatherpocket__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.AuthService/RefreshToken',
            weatherpocket__pb2.RefreshTokenRequest.SerializeToString,
            weatherpocket__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.AuthService/GetMe',
            weatherpocket__pb2.GetMeRequest.SerializeToString,
            weatherpocket__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConversationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateConversation = channel.unary_unary(
                '/weatherpocket.v1.ConversationService/CreateConversation',
                request_serializer=weatherpocket__pb2.CreateConversationRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.ConversationResponse.FromString,
                _registered_method=True)
        self.ListConversations = channel.unary_unary(
                '/weatherpocket.v1.ConversationService/ListConversations',
                request_serializer=weatherpocket__pb2.ListConversationsRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.ListConversationsResponse.FromString,
                _registered_method=True)
        self.GetConversation = channel.unary_unary(
                '/weatherpocket.v1.ConversationService/GetConversation',
                request_serializer=weatherpocket__pb2.GetConversationRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.ConversationResponse.FromString,
                _registered_method=True)
        self.DeleteConversation = channel.unary_unary(
                '/weatherpocket.v1.ConversationService/DeleteConversation',
                request_serializer=weatherpocket__pb2.DeleteConversationRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.Empty.FromString,
                _registered_method=True)


class ConversationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConversation,
                    request_deserializer=weatherpocket__pb2.CreateConversationRequest.FromString,
                    response_serializer=weatherpocket__pb2.ConversationResponse.SerializeToString,
            ),
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=weatherpocket__pb2.ListConversationsRequest.FromString,
                    response_serializer=weatherpocket__pb2.ListConversationsResponse.SerializeToString,
            ),
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=weatherpocket__pb2.GetConversationRequest.FromString,
                    response_serializer=weatherpocket__pb2.ConversationResponse.SerializeToString,
            ),
            'DeleteConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversation,
                    request_deserializer=weatherpocket__pb2.DeleteConversationRequest.FromString,
                    response_serializer=weatherpocket__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weatherpocket.v1.ConversationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weatherpocket.v1.ConversationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConversationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.ConversationService/CreateConversation',
            weatherpocket__pb2.CreateConversationRequest.SerializeToString,
            weatherpocket__pb2.ConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.ConversationService/ListConversations',
            weatherpocket__pb2.ListConversationsRequest.SerializeToString,
            weatherpocket__pb2.ListConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.ConversationService/GetConversation',
            weatherpocket__pb2.GetConversationRequest.SerializeToString,
            weatherpocket__pb2.ConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.ConversationService/DeleteConversation',
            weatherpocket__pb2.DeleteConversationRequest.SerializeToString,
            weatherpocket__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChatServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateConversationFromPrompt = channel.unary_unary(
                '/weatherpocket.v1.ChatService/CreateConversationFromPrompt',
                request_serializer=weatherpocket__pb2.CreateConversationPromptRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.CreateConversationPromptResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/weatherpocket.v1.ChatService/SendMessage',
                request_serializer=weatherpocket__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.StreamMessage = channel.unary_stream(
                '/weatherpocket.v1.ChatService/StreamMessage',
                request_serializer=weatherpocket__pb2.StreamMessageRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.StreamMessageChunk.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/weatherpocket.v1.ChatService/GetMessages',
                request_serializer=weatherpocket__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.GetMessagesResponse.FromString,
                _registered_method=True)


class ChatServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateConversationFromPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateConversationFromPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConversationFromPrompt,
                    request_deserializer=weatherpocket__pb2.CreateConversationPromptRequest.FromString,
                    response_serializer=weatherpocket__pb2.CreateConversationPromptResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=weatherpocket__pb2.SendMessageRequest.FromString,
                    response_serializer=weatherpocket__pb2.SendMessageResponse.SerializeToString,
            ),
            'StreamMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessage,
                    request_deserializer=weatherpocket__pb2.StreamMessageRequest.FromString,
                    response_serializer=weatherpocket__pb2.StreamMessageChunk.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=weatherpocket__pb2.GetMessagesRequest.FromString,
                    response_serializer=weatherpocket__pb2.GetMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weatherpocket.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weatherpocket.v1.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateConversationFromPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.ChatService/CreateConversationFromPrompt',
            weatherpocket__pb2.CreateConversationPromptRequest.SerializeToString,
            weatherpocket__pb2.CreateConversationPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.ChatService/SendMessage',
            weatherpocket__pb2.SendMessageRequest.SerializeToString,
            weatherpocket__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/weatherpocket.v1.ChatService/StreamMessage',
            weatherpocket__pb2.StreamMessageRequest.SerializeToString,
            weatherpocket__pb2.StreamMessageChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.ChatService/GetMessages',
            weatherpocket__pb2.GetMessagesRequest.SerializeToString,
            weatherpocket__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DocumentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadPdf = channel.unary_unary(
                '/weatherpocket.v1.DocumentService/UploadPdf',
                request_serializer=weatherpocket__pb2.UploadPdfRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.UploadPdfResponse.FromString,
                _registered_method=True)
        self.UploadPdfStream = channel.unary_stream(
                '/weatherpocket.v1.DocumentService/UploadPdfStream',
                request_serializer=weatherpocket__pb2.UploadPdfRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.UploadPdfProgressChunk.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/weatherpocket.v1.DocumentService/ListFiles',
                request_serializer=weatherpocket__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/weatherpocket.v1.DocumentService/DeleteFile',
                request_serializer=weatherpocket__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.Empty.FromString,
                _registered_method=True)
        self.GetChunk = channel.unary_unary(
                '/weatherpocket.v1.DocumentService/GetChunk',
                request_serializer=weatherpocket__pb2.GetChunkRequest.SerializeToString,
                response_deserializer=weatherpocket__pb2.ChunkResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def UploadPdf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadPdfStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadPdf': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPdf,
                    request_deserializer=weatherpocket__pb2.UploadPdfRequest.FromString,
                    response_serializer=weatherpocket__pb2.UploadPdfResponse.SerializeToString,
            ),
            'UploadPdfStream': grpc.unary_stream_rpc_method_handler(
                    servicer.UploadPdfStream,
                    request_deserializer=weatherpocket__pb2.UploadPdfRequest.FromString,
                    response_serializer=weatherpocket__pb2.UploadPdfProgressChunk.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=weatherpocket__pb2.ListFilesRequest.FromString,
                    response_serializer=weatherpocket__pb2.ListFilesResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=weatherpocket__pb2.DeleteFileRequest.FromString,
                    response_serializer=weatherpocket__pb2.Empty.SerializeToString,
            ),
            'GetChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChunk,
                    request_deserializer=weatherpocket__pb2.GetChunkRequest.FromString,
                    response_serializer=weatherpocket__pb2.ChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weatherpocket.v1.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weatherpocket.v1.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadPdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.DocumentService/UploadPdf',
            weatherpocket__pb2.UploadPdfRequest.SerializeToString,
            weatherpocket__pb2.UploadPdfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadPdfStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/weatherpocket.v1.DocumentService/UploadPdfStream',
            weatherpocket__pb2.UploadPdfRequest.SerializeToString,
            weatherpocket__pb2.UploadPdfProgressChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.DocumentService/ListFiles',
            weatherpocket__pb2.ListFilesRequest.SerializeToString,
            weatherpocket__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.DocumentService/DeleteFile',
            weatherpocket__pb2.DeleteFileRequest.SerializeToString,
            weatherpocket__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weatherpocket.v1.DocumentService/GetChunk',
            weatherpocket__pb2.GetChunkRequest.SerializeToString,
            weatherpocket__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
